//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthX.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthX.Localization.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (1€ app fee applies).
        /// </summary>
        public static string AppFeeText {
            get {
                return ResourceManager.GetString("AppFeeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Approx. .
        /// </summary>
        public static string ApproxText {
            get {
                return ResourceManager.GetString("ApproxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At your Home Pharmacy:.
        /// </summary>
        public static string AtHomePharmacyText {
            get {
                return ResourceManager.GetString("AtHomePharmacyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Order now and get notified when ready for you!.
        /// </summary>
        public static string AvailableOrderText {
            get {
                return ResourceManager.GetString("AvailableOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Available on Order!.
        /// </summary>
        public static string AvailableOrderTextShort {
            get {
                return ResourceManager.GetString("AvailableOrderTextShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Available - Reserve now and secure availability!.
        /// </summary>
        public static string AvailableText {
            get {
                return ResourceManager.GetString("AvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Available!.
        /// </summary>
        public static string AvailableTextShort {
            get {
                return ResourceManager.GetString("AvailableTextShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Awaiting Validation.
        /// </summary>
        public static string AwaitingValidationText {
            get {
                return ResourceManager.GetString("AwaitingValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Closed. Opening at .
        /// </summary>
        public static string ClosedOpeningAt {
            get {
                return ResourceManager.GetString("ClosedOpeningAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Closed today..
        /// </summary>
        public static string ClosedToday {
            get {
                return ResourceManager.GetString("ClosedToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CONFIRM ORDER.
        /// </summary>
        public static string ConfirmOrderText {
            get {
                return ResourceManager.GetString("ConfirmOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contains: .
        /// </summary>
        public static string ContainsText {
            get {
                return ResourceManager.GetString("ContainsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current Purchases.
        /// </summary>
        public static string CurrentPurchasesText {
            get {
                return ResourceManager.GetString("CurrentPurchasesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error!.
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your favorites :.
        /// </summary>
        public static string FavoritesText {
            get {
                return ResourceManager.GetString("FavoritesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Few left! Reserve now to secure it for you!.
        /// </summary>
        public static string FewLeftText {
            get {
                return ResourceManager.GetString("FewLeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Few left!.
        /// </summary>
        public static string FewLeftTextShort {
            get {
                return ResourceManager.GetString("FewLeftTextShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find Medicine.
        /// </summary>
        public static string FindMedicineTitle {
            get {
                return ResourceManager.GetString("FindMedicineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Medicines.
        /// </summary>
        public static string GenericMedicinesText {
            get {
                return ResourceManager.GetString("GenericMedicinesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        public static string GenericOK {
            get {
                return ResourceManager.GetString("GenericOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pharmacies.
        /// </summary>
        public static string GenericPharmaciesText {
            get {
                return ResourceManager.GetString("GenericPharmaciesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GPS not available.
        /// </summary>
        public static string GpsNotAvailableText {
            get {
                return ResourceManager.GetString("GpsNotAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image of Prescription.
        /// </summary>
        public static string ImageOfPrescriptionText {
            get {
                return ResourceManager.GetString("ImageOfPrescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Infos.
        /// </summary>
        public static string InfosText {
            get {
                return ResourceManager.GetString("InfosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In Preparation....
        /// </summary>
        public static string InPreparationText {
            get {
                return ResourceManager.GetString("InPreparationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à More Infos.
        /// </summary>
        public static string MoreInfosTitle {
            get {
                return ResourceManager.GetString("MoreInfosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nearest where available:.
        /// </summary>
        public static string NearestAvailableText {
            get {
                return ResourceManager.GetString("NearestAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have no current purchases..
        /// </summary>
        public static string NoCurrentPurchasesText {
            get {
                return ResourceManager.GetString("NoCurrentPurchasesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Sell Restrictions.
        /// </summary>
        public static string NoSellRestrictionsText {
            get {
                return ResourceManager.GetString("NoSellRestrictionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sorry, this product is currently not available..
        /// </summary>
        public static string NotAvailableText {
            get {
                return ResourceManager.GetString("NotAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Currently not available.
        /// </summary>
        public static string NotAvailableTextShort {
            get {
                return ResourceManager.GetString("NotAvailableTextShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not Paid.
        /// </summary>
        public static string NotPaidText {
            get {
                return ResourceManager.GetString("NotPaidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Only available in pharmacies.
        /// </summary>
        public static string OnlyPharmaciesText {
            get {
                return ResourceManager.GetString("OnlyPharmaciesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Only available on prescription.
        /// </summary>
        public static string OnlyPrescriptionText {
            get {
                return ResourceManager.GetString("OnlyPrescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opened until .
        /// </summary>
        public static string OpenedUntil {
            get {
                return ResourceManager.GetString("OpenedUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Order at .
        /// </summary>
        public static string OrderAtString {
            get {
                return ResourceManager.GetString("OrderAtString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Order from Prescription.
        /// </summary>
        public static string OrderFromPrescriptionText {
            get {
                return ResourceManager.GetString("OrderFromPrescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Order Now!.
        /// </summary>
        public static string OrderNowText {
            get {
                return ResourceManager.GetString("OrderNowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Order.
        /// </summary>
        public static string OrderText {
            get {
                return ResourceManager.GetString("OrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paid.
        /// </summary>
        public static string PaidText {
            get {
                return ResourceManager.GetString("PaidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured during transaction. Operation cancelled..
        /// </summary>
        public static string PaymentFailureText {
            get {
                return ResourceManager.GetString("PaymentFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à When would you like to pay?.
        /// </summary>
        public static string PaymentQuestion {
            get {
                return ResourceManager.GetString("PaymentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pay Now.
        /// </summary>
        public static string PayNowText {
            get {
                return ResourceManager.GetString("PayNowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pay on Pickup (1€ app fee applies).
        /// </summary>
        public static string PayPickupText {
            get {
                return ResourceManager.GetString("PayPickupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prescription: .
        /// </summary>
        public static string PrescriptionText {
            get {
                return ResourceManager.GetString("PrescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning! This medicine is only available on prescription. You will be asked for a prescription at purchase.
        /// </summary>
        public static string PrescriptionWarningText {
            get {
                return ResourceManager.GetString("PrescriptionWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Purchase.
        /// </summary>
        public static string PurchaseText {
            get {
                return ResourceManager.GetString("PurchaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ready.
        /// </summary>
        public static string ReadyText {
            get {
                return ResourceManager.GetString("ReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You may be looking for....
        /// </summary>
        public static string RecommendationText {
            get {
                return ResourceManager.GetString("RecommendationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured while processing your reservation. Please try again later..
        /// </summary>
        public static string ReservationFailureText {
            get {
                return ResourceManager.GetString("ReservationFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reservations.
        /// </summary>
        public static string ReservationsText {
            get {
                return ResourceManager.GetString("ReservationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your reservation was successful. You can monitor it in the Shop.&quot;.
        /// </summary>
        public static string ReservationSuccessText {
            get {
                return ResourceManager.GetString("ReservationSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reservation.
        /// </summary>
        public static string ReservationText {
            get {
                return ResourceManager.GetString("ReservationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reserve!.
        /// </summary>
        public static string ReserveText {
            get {
                return ResourceManager.GetString("ReserveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Searching at :.
        /// </summary>
        public static string SearchingAtText {
            get {
                return ResourceManager.GetString("SearchingAtText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search Medicine ....
        /// </summary>
        public static string SearchMedicinePlaceholder {
            get {
                return ResourceManager.GetString("SearchMedicinePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show this when picking up your order..
        /// </summary>
        public static string ShowOnPickupText {
            get {
                return ResourceManager.GetString("ShowOnPickupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status: .
        /// </summary>
        public static string StatusText {
            get {
                return ResourceManager.GetString("StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Success!.
        /// </summary>
        public static string SuccessText {
            get {
                return ResourceManager.GetString("SuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your Home Pharmacy.
        /// </summary>
        public static string YourHomePharmacyText {
            get {
                return ResourceManager.GetString("YourHomePharmacyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your Order.
        /// </summary>
        public static string YourOrderTitle {
            get {
                return ResourceManager.GetString("YourOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You where searching at:.
        /// </summary>
        public static string YouWereSearchingAtText {
            get {
                return ResourceManager.GetString("YouWereSearchingAtText", resourceCulture);
            }
        }
    }
}
